services:
  isaac-sim:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        USER_ID: ${USER_ID:?}
        GROUP_ID: ${GROUP_ID:?}
        SHARED_GROUP_ID: ${SHARED_GROUP_ID}
        DOCKER_USERNAME: ${DOCKER_USERNAME:?}
    image: ${USERNAME:?}/nvsynth
    user: ${USER_ID:?}:${GROUP_ID:?}
    volumes:
      - .:/nvsynth
      # food data volume
      - /pub2/nrc/aging/snair_iccv_data:/food
      # isaac-sim related volumes
      - ~/docker/isaac-sim/cache/kit:/isaac-sim/kit/cache/kit
      - ~/docker/isaac-sim/cache/ov:/user/.cache/ov
      - ~/docker/isaac-sim/cache/pip:/user/.cache/pip
      - ~/docker/isaac-sim/cache/glcache:/user/.cache/nvidia/GLCache
      - ~/docker/isaac-sim/cache/computecache:/user/.nv/ComputeCache
      - ~/docker/isaac-sim/logs:/user/.nvidia-omniverse/logs
      - ~/docker/isaac-sim/data:/user/.local/share/ov/data
      - ~/docker/isaac-sim/documents:/user/Documents
    environment:
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
    network_mode: "host"
    ipc: host
    tty: True
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
