model {
  file: "model.sdf"
}
name: "Threshold_Dinner_Plate_Square_Rim_White_Porcelain"
description: "Threshold Dinner Plate, Square Rim, White, Porcelain"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Threshold"
}
annotations {
  key: "gtin"
  value: "00727870053300"
}
annotations {
  key: "sku"
  value: "00727870053300"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
