FROM nvcr.io/nvidia/isaac-sim:2022.2.1 AS base

# install dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libcurl4-openssl-dev build-essential && \
    apt-get clean

# personal dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    wget lsof git neovim

COPY . /nvsynth

# configure omni-provided python
RUN echo "export PATH=$PATH:/isaac-sim/kit/python/bin\n" >> /root/.bashrc && \
    echo "source /nvsynth/docker/setup_docker_env.sh\n" >> /root/.bashrc && \
    ln -s /isaac-sim/kit/python/bin/python3 /isaac-sim/kit/python/bin/python && \
    /isaac-sim/kit/python/bin/python -m pip install --upgrade pip && \
    /isaac-sim/kit/python/bin/pip install -r /nvsynth/docker/requirements.docker.txt

# resolves segfault caused by multiple ICD configs
RUN mv /etc/vulkan/icd.d/nvidia_icd.json /etc/vulkan/icd.d/nvidia_icd.json.old

# incredibly hacky
RUN cp -r /isaac-sim/extscache/* /isaac-sim/kit/extscore

# overrides entrypoint from base image
WORKDIR /nvsynth
ENTRYPOINT bash
