# tyro YAML.
!dataclass:SceneItems
food_items:
  - !dataclass:FoodItemConfig
    model_label: id_100_steak_153g
    pose: !dataclass:PoseConfig
      orientation: !dataclass:EulerOrientation
        pitch: 0
        roll: 90
        yaw: -45
      position: !dataclass:CylindricalPosition
        r: 0.06
        theta: 330
        z: 0.2
    scale: null
    static: false
  - !dataclass:FoodItemConfig
    model_label: id_59_rib_98g
    pose: !dataclass:PoseConfig
      orientation: !dataclass:EulerOrientation
        pitch: 0
        roll: 90
        yaw: 0
      position: !dataclass:CylindricalPosition
        r: 0.05
        theta: 260
        z: 0.2
    scale: null
    static: false
  - !dataclass:FoodItemConfig
    model_label: id_60_rib_101g
    pose: !dataclass:PoseConfig
      orientation: !dataclass:EulerOrientation
        pitch: 0
        roll: 90
        yaw: 0
      position: !dataclass:CylindricalPosition
        r: 0.08
        theta: 230
        z: 0.2
    scale: null
    static: false
  - !dataclass:FoodItemConfig
    model_label: id_96_corn_81g
    pose: !dataclass:PoseConfig
      orientation: !dataclass:EulerOrientation
        pitch: 0
        roll: 0
        yaw: 90
      position: !dataclass:CylindricalPosition
        r: 0.07
        theta: 140
        z: 0.2
    scale: null
    static: false
  - !dataclass:FoodItemConfig
    model_label: id_97_french_fry_6g
    pose: !dataclass:PoseConfig
      orientation: !dataclass:EulerOrientation
        pitch: 0
        roll: 0
        yaw: 45
      position: !dataclass:CylindricalPosition
        r: 0.07
        theta: 30
        z: 0.2
    scale: null
    static: false
  - !dataclass:FoodItemConfig
    model_label: id_97_french_fry_6g
    pose: !dataclass:PoseConfig
      orientation: !dataclass:EulerOrientation
        pitch: 0
        roll: 0
        yaw: 50
      position: !dataclass:CylindricalPosition
        r: 0.07
        theta: 30
        z: 0.25
    scale: null
    static: false
  - !dataclass:FoodItemConfig
    model_label: id_97_french_fry_6g
    pose: !dataclass:PoseConfig
      orientation: !dataclass:EulerOrientation
        pitch: 0
        roll: 0
        yaw: 40
      position: !dataclass:CylindricalPosition
        r: 0.07
        theta: 30
        z: 0.15
    scale: null
    static: false
