---
scene:
  num_steps: 200
  camera:
    position: [0, 200, 100]
    horizontal_range:
      max: 360
      steps: 4
    vertical_range:
      max: 45
      steps: 3
  layer1:
    name: "sushi"
    usd_path: "/assets/food/id-39-costco-california-sushi-roll-1-27g/poly_obj.usd"
    scale: 15
    num: 12
    position: [[0, 0, 30], [1, 12, 0]]
    rotation: 0
    static_friction: 0.9
    dynamic_friction: 0.9
    restitution: 0.05
    mass: 100
