---
scene:
  num_steps: 200
  camera:
    position: [0, 200, 100]
    horizontal_range:
      max: 360
      steps: 4
    vertical_range:
      max: 45
      steps: 3
  layer1:
    name: "wing"
    usd_path: "/assets/food/id-21-chicken-wing-27g/textured_obj.usd"
    scale: [50, 70]
    num: 12
    position: [[0, 0, 30], [5, 2, 0]]
    rotation: [[0, 0, 0], [360, 360, 360]]
    angular_velocity: [[0, 0, 0], [100, 100, 100]]
    static_friction: 0.9
    dynamic_friction: 0.9
    restitution: 0.05
    mass: 100
